#!/usr/bin/env sh

CPU_PATH="/sys/devices/system/cpu/cpu0/cpufreq/"
MIN="cpuinfo_min_freq"
MAX="cpuinfo_max_freq"
CUR="cpuinfo_cur_freq"


echo "current freq" "$(sudo cat $CPU_PATH$CUR)"
echo "max freq" "$(sudo cat $CPU_PATH$MAX)"
echo "min freq" "$(sudo cat $CPU_PATH$MIN)"
